### ISSUE TITLE
Npx 2.0 probe geometry

### ISSUE THREAD

**Issue by gomesteixeira** [petersaj/neuropixels_trajectory_explorer#1]
Are there any plans to include neuropixels 2.0 probes on this tool?
We like this tool a lot, but we currently have to do some math in order to use it to plan for npx 2.0 insertions.
It would be great if one could choose which npx probe to use, or alternatively define the probe geometrically (eg using shank length and inter-shank distance).
I would be happy to contribute to this feature, if that's part of your plans.
Thanks in advance!

**Comment by petersaj** [comment]
Hi José - for sure I'd like to add 2.0/4-shank to this, I probably won't be able to work on this for a few months though. In the meantime, some other options:

Nick Steinmetz's lab's recently put out their own trajectory explorer, this includes 4 shanks: 
https://github.com/dbirman/NPTrajectoryPlanner

A student in our lab added 4-shank functions to an older version of my GUI, it's missing newer features but might be good for now:
https://github.com/cortex-lab/allenCCF/blob/master/Browsing%20Functions/allen_ccf_npx_4shank_spherical.m

**Comment by gomesteixeira** [comment]
Hi Andy,

Thanks for the suggestions, it seems they should do the trick for us!

Keep up the great work.
