### ISSUE TITLE
2 or more probes trajectory planning

### ISSUE THREAD

**Issue by cyf203** [petersaj/neuropixels_trajectory_explorer#11]
Hi, I wonder if your tool allows multiprobe trajectory planning.

I knew that pinpoint can. But they haven't released a version for rat. 

Thank you!

**Comment by petersaj** [comment]
The mouse version can at the moment - the rat version hasn't been upgraded in a long time. 

The most efficient solution is to make the up-to-date GUI compatible with the rat atlas, I've put that on the to-do list. To be notified when this is done, subscribe to this issue: https://github.com/petersaj/neuropixels_trajectory_explorer/issues/13
