### ISSUE TITLE
Dropdown menu disappeared 

### ISSUE THREAD

**Issue by Andrea3v** [petersaj/neuropixels_trajectory_explorer#15]
It seems the dropdown menu (when running within MATLAB) has vanished from both mouse and rat:

![dropdown](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/87669012/4b43c52c-2a84-4a2d-8fdd-6d4dab4097be)

the standalone still has it though. I tried different MATLAB installations but problem persists.
any help to bring it back would be very appreciated!

thank you
Andrea

**Comment by petersaj** [comment]
Hi Andrea - it still shows up for me (just mouse version - rat version is lagging behind changes so doesn't have it yet), can you send a screenshot of what yours looks like? Does it appear if you make the window bigger?

**Comment by Andrea3v** [comment]
Hi Andy, thank you for the quick reply!
here's a screenshot:
![image](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/87669012/07649534-838f-4103-83e2-03074cc0f904)
resizing the window doesn't make it appear, unfortunately.
Just to confirm: the rat version never had it?
I'm mainly interested in rescaling the atlas according to Bregma-lambda distance. I started recording in rats and realized they have a quite significant range of measures (7.5-10mm), is there a workaround I can use to account for that (maybe through the code or something)? 

thank you in advance for any help or suggestion you may have
~Andrea
PS I love this tool!

**Comment by petersaj** [comment]
Hi Andrea - that's a very old version of the GUI, can you try pulling the latest repo and trying again? I'm not sure how you've gotten the old one. 

That's right that the rat version never had it, I'm hoping to merge the GUIs (to get an alert, subscribe to this issue: https://github.com/petersaj/neuropixels_trajectory_explorer/issues/13), but probably won't be able to this month. Unfortunately until I do that you can't rescale the rat atlas with this GUI.

**Comment by Andrea3v** [comment]
you are right! I didn't notice I was running a version from Feb 🤦🏼‍♂️ a conflict was preventing matlab to pull the latest version of the code. indeed the new code has the dropdown! 
thank you for your help and looking forward to the next upgrade!
PS by changing `clim([0 300])` to `caxis([0 300])` on line 137 would help run the code in MATLAB versions before 2022!

**Comment by petersaj** [comment]
Great - sure, I switched `clim`s to `caxis`s
