### ISSUE TITLE
Gerbil atlas

### ISSUE THREAD

**Issue by Lexi13** [petersaj/neuropixels_trajectory_explorer#16]
Would it be possible to integrate the atlas for Mongolian Gerbils?

The original authors published the atlas here but I am assuming you would need a different format:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5005445/

**Comment by petersaj** [comment]
As far as I can see, the only thing available is the segmented coronal images? In order to use it in a GUI, it'd need to be a downloadable volumetric atlas.

**Comment by Lexi13** [comment]
Can you clarify what you mean by volumetric? 3D images? I can potentially reach out to the arthurs but I am not exactly sure what to ask for.

**Comment by petersaj** [comment]
Right - a 3D matrix of parcellated region labels (and ideally a paired 3D matrix of anatomical images). 

I'll be unable to help with this at the moment, but adopting new atlases is something that Pinpoint is actively developing, so might be worth moving to that (https://github.com/VirtualBrainLab/Pinpoint).

**Comment by Lexi13** [comment]
Ok thank you for the input
