### ISSUE TITLE
Probe insertion depth not right

### ISSUE THREAD

**Issue by zmingmin** [petersaj/neuropixels_trajectory_explorer#18]
Hi,
It seems the probe insertion depth is not right.  Am I missing something? 

Thanks a lot!

![image](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/146054957/ce113d1f-94bc-48eb-aae1-c95a031a1009)

**Comment by petersaj** [comment]
Can I check: are you working with the latest version of the GUI?

From your picture, my guess is that your probe trajectory is entirely outside the brain, in which case the coordinates do not update. I believe I added an update a while ago that shows a message stating something like "probe trajectory doesn't intersect with the brain", which means that you might be working with slightly old code.

**Comment by zmingmin** [comment]
Hi, Andy, thanks for your reply. 
I am using the newest version. 

I cropped two new ones when the probe are completely inside the brain, and the probe depths are still strange (too big).

It seems the data updated in the variable **probe_depths** is not correct. 

Thanks again!

![image](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/146054957/249296b9-10de-4995-9626-96bb819f8906)
![image](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/146054957/2f568c8d-af1e-4700-abd3-8d52bee9d8bf)

**Comment by petersaj** [comment]
I wasn't able to replicate your error by going to the coordinates in your screenshot above, I tried all 3 methods of moving the probe (manually, setting entry, setting endpoint) and the depth coordinate looks normal in all cases: 

![image](https://github.com/petersaj/neuropixels_trajectory_explorer/assets/17985056/bd5aa218-8f90-4b90-893c-22c464a8d455)

Could you tell me the steps you're doing so I could try to get that bug on my end? And is the depth coordinate wrong even when you first open the GUI, or only after you move it?

**Comment by zmingmin** [comment]
(When I open the GUI, the depth coordinate is wrong without any movement. )

I found there was a conflict with some functions in my toolbox.  Once I removed my toolbox, everything was fine. 

I really like the GUI! Thanks a lot!
