### ISSUE TITLE
cannot add 3 or more probes

### ISSUE THREAD

**Issue by chongtianyifa** [petersaj/neuropixels_trajectory_explorer#19]
When I add 2 more probes, the probe color can not be assigned correctly.
Changing line 2400 to the following solved the issue:
`if any(~selected_probe_idx)
    ind_unselected = find(~selected_probe_idx);
    for ii=ind_unselected
        set(gui_data.probe(ii).line,'color',unselected_color);
    end
end`

**Comment by petersaj** [comment]
Thanks, good find, I've just pushed a bugfix
