### ISSUE TITLE
Allow for 4-shank trajectories

### ISSUE THREAD

**Issue by eabhorrocks** [petersaj/neuropixels_trajectory_explorer#2]
Any chance of adding 4-shank functionality, similar to the previous version?

Thanks
Edd

**Comment by petersaj** [comment]
Hi Edd - it's a popular request for folks with access to 4-shank probes, I probably won't be able to get to it for a while but in the mean time, you could try this tool that does that: https://github.com/dbirman/NPTrajectoryPlanner

**Comment by petersaj** [comment]
(I've put this in the to-upgrade list, to be notified when this is completed, subscribe to this issue: https://github.com/petersaj/neuropixels_trajectory_explorer/issues/12)
