### ISSUE TITLE
Startup failure with standalone application when CCF atlas directory changed

### ISSUE THREAD

**Issue by wangxuanyu0419** [petersaj/neuropixels_trajectory_explorer#22]
Hi Peter!
I had an issue with the deployed version of the Neuropixels trajectory explorer. I moved the CCF files to another directory because I ran out of disk storage. However, the software does not start with a relocation request but terminates with the following error:
```
File not found: xxxxx\template_volume_10um.npy
Error in => neuropixels_trajectory_explorer.m at line 80
```
I tried to reinstall the software, or change the `nte_paths.mat` under `./nte_deployed`. Neither worked.
I wonder where is the file location cashed and can I remove this history?

**Comment by petersaj** [comment]
Hi Xuanyu - just checking: do you mean the deployed version (e.g. without Matlab, the undeployed version run through Matlab just needs the folder with the CCF to be added to the Matlab path)? 

I've uploaded a fix where it checks for the files and asks for the path again if it can't find them - do you want to update and see if the problem is fixed for you?

**Comment by wangxuanyu0419** [comment]
Thank you for your reply! Oh sorry for the typo, I mean the deployed version (`.exe`). Did you just fix the matlab `.m` file? It would be helpful to also fix the `.exe`.

**Comment by petersaj** [comment]
Yes, I fixed the `.exe` file (that's the deployed version) for for the issue you mentioned, if you wanted to update the code and try it

**Comment by wangxuanyu0419** [comment]
Sadly, I still got the same error. I uninstalled it via the Windows control panel and pulled it locally, reinstalled it with the `.exe`. The error message was still there.

**Comment by wangxuanyu0419** [comment]
The undeployed version was working fine.

**Comment by petersaj** [comment]
Oops apologies, I forgot to copy the updated installer into the main page - I've done that now, do you want to try again?

**Comment by wangxuanyu0419** [comment]
Yes, all set! Thank you!

**Comment by wangxuanyu0419** [comment]
Somehow I have issue opening it after reinstalled with the new executive file. It runs but stays in the background, taking up CPU and memory resources but no window is opened. I retrieved from the last commit `6d8c3b8` and was working fine.

**Comment by petersaj** [comment]
I think I found the issue - could you pull the latest version and try again?
