### ISSUE TITLE
Error when trying to annotate without having added a probe

### ISSUE THREAD

**Issue by MDrueke** [petersaj/neuropixels_trajectory_explorer#26]
I'm aware that this is not a common use case, but maybe you want to avoid this error by selected a default location if there is no probe. The error is:

`Unrecognized field name "selected_probe".

Error in neuropixels_trajectory_explorer>update_slice (line 424)
        gui_data.probe(gui_data.selected_probe).trajectory, ...

Error in neuropixels_trajectory_explorer>visibility_av_slice (line 1477)
update_slice(probe_atlas_gui);
 
Error while evaluating Menu Callback.`

**Comment by petersaj** [comment]
Thanks - just fixed and updated the repo
