### ISSUE TITLE
No Download the Allen CCF mouse atlas.

### ISSUE THREAD

**Issue by imontiel92** [petersaj/neuropixels_trajectory_explorer#3]
Hi Peter,
How can I download the Allen CCF mouse atlas with the re-formatted version?  I entered the link, but it appeared an error message.
Thanks
Ivan

**Comment by petersaj** [comment]
That's curious, I even accessed it earlier today, looks like the permissions were changed for some reason. 

The files are large, so I've uploaded them on OSF, can you try downloading them from here? https://osf.io/fv7ed/

If that works, I'll make that the new link for downloading

**Comment by petersaj** [comment]
I've been told that other folks can download from this link, so I've changed it in the instructions

**Comment by imontiel92** [comment]
Thank you!
